@apiUrl = http://localhost:5000/api
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQWRtaW4iLCJuYmYiOjE2MjQ2NTk5NzQsImV4cCI6MTYyNDc0NjM3NCwiaWF0IjoxNjI0NjU5OTc0LCJpc3MiOiJFbXBsb3llZSBNYW5hZ2VtZW50IFN5c3RlbSJ9.0ipiIkUxKnV3QrmEEslTphR6OiLjyXyL7rreyU2JuytCj6yHfbMNeO_7yKxmlCo5wI4Z8bjMOYDRuEs6cBlK4g


POST {{apiUrl}}/account/login
Content-Type: application/json

{
    "username": "alice",
    "password": "Password@1"
}

# {
#     "username": "bob",
#     "password": "Password@1"
# }

###

GET {{apiUrl}}/employee
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/employee/1
Authorization: Bearer {{token}}

###

POST {{apiUrl}}/employee
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Sabina",
  "lastName": "Hameed",
  "designation": "Nutritionist",
  "department": "Fitness"
}

###

PUT {{apiUrl}}/employee/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Sabina",
  "lastName": "Hameed",
  "designation": "Nutritionist",
  "department": "Fitness"
}

###

DELETE  {{apiUrl}}/employee/15
Authorization: Bearer {{token}}
